version: '3.0'
services:
  monokel:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        # the mount bindings automatically identified based on the config.py
        # hashed locations will be used and generated automatically
        - /tmp:/8ba9a8a
    environment:
        # the state information that we are running main.py inside the container
        - CONTAINER=1
        # reference to the used mount bindings
        - MOUNT_8ba9a8a=/tmp
    restart: unless-stopped